### ISSUE TITLE
Mankas permesilojn

### ISSUE THREAD

**Issue by nicolasmaia** [dotevo/esperantmapo#1]
Mi ne kontrolis ĉiujn dosierojn, sed mi vidas, ke kelkaj de ili ne enhavas permesilo-informon. Mi ankaŭ sugestus aldoni LICENSE.md-dosieron, pro ke Github sciu tuj.

**Comment by dotevo** [comment]
https://github.com/dotevo/esperantmapo/commit/013f0a47b9b38b36366e348cb056ea03a7433e22
