### ISSUE TITLE
Etikedoj tro proksimas unu al la alia

### ISSUE THREAD

**Issue by nicolasmaia** [dotevo/esperantmapo#2]
Legi etikedojn en Eŭropo estas preskaŭ neebla ĉi-momente.

**Comment by nicolasmaia** [comment]
Eble oni povus uzi solvon simile al tiu: https://github.com/tejoesperanto/pasportaservo/issues/137

**Comment by dotevo** [comment]
Tejo uzas mapbox. Mi pensas ke mi povas solvi tiun problemon with 
https://github.com/MazeMap/Leaflet.LayerGroup.Collision
Sed mi pensas ke neniu uzas mian mapon do mi ne skribas multe.

**Comment by dotevo** [comment]
Done
