### ISSUE TITLE
Montru esperanto=yes

### ISSUE THREAD

**Issue by nicolasmaia** [dotevo/esperantmapo#3]
`esperanto=yes` estas etikedo por E-asocioj kaj iaj aliaj ZEOj. Indas montri ĝin en la mapo ankaŭ.

**Comment by dotevo** [comment]
Nemulte da datumoj pli. http://overpass-turbo.eu/s/lMt

**Comment by nicolasmaia** [comment]
Ne maltrankviliĝu pri tio, mi prilaboros por pligrandigi tiun nombron :)
